/*
    MBed OS Target Define Header.
    This contains all of the #defines specific to your target and device.
    It is prepended to every source file using the -include compiler option.
    AUTOGENERATED by configure_for_target.py.  DO NOT EDIT!
    */

#define ARM_MATH_CM3 1
#define COMPONENT_NSPE 1
#define COMPONENT_PSA_SRV_EMUL 1
#define COMPONENT_PSA_SRV_IMPL 1
#define DEVICE_ANALOGIN 1
#define DEVICE_ANALOGOUT 1
#define DEVICE_CAN 1
#define DEVICE_DEBUG_AWARENESS 1
#define DEVICE_EMAC 1
#define DEVICE_ETHERNET 1
#define DEVICE_FLASH 1
#define DEVICE_I2C 1
#define DEVICE_I2CSLAVE 1
#define DEVICE_INTERRUPTIN 1
#define DEVICE_LOCALFILESYSTEM 1
#define DEVICE_MPU 1
#define DEVICE_PORTIN 1
#define DEVICE_PORTINOUT 1
#define DEVICE_PORTOUT 1
#define DEVICE_PWMOUT 1
#define DEVICE_RESET_REASON 1
#define DEVICE_RTC 1
#define DEVICE_SEMIHOST 1
#define DEVICE_SERIAL 1
#define DEVICE_SERIAL_FC 1
#define DEVICE_SLEEP 1
#define DEVICE_SPI 1
#define DEVICE_SPISLAVE 1
#define DEVICE_STDIO_MESSAGES 1
#define DEVICE_USBDEVICE 1
#define DEVICE_USTICKER 1
#define DEVICE_WATCHDOG 1
#define MBED_BUILD_TIMESTAMP 1589508918.9952729
#define TARGET_CORTEX 1
#define TARGET_CORTEX_M 1
#define TARGET_LIKE_CORTEX_M3 1
#define TARGET_LIKE_MBED 1
#define TARGET_LPC1768 1
#define TARGET_LPC176X 1
#define TARGET_LPCTarget 1
#define TARGET_M3 1
#define TARGET_MBED_LPC1768 1
#define TARGET_NAME LPC1768
#define TARGET_NXP 1
#define TARGET_NXP_EMAC 1
#define TARGET_RELEASE 1
#define TOOLCHAIN_GCC 1
#define TOOLCHAIN_GCC_ARM 1
#define __CMSIS_RTOS 1
#define __CORTEX_M3 1
#define __MBED_CMSIS_RTOS_CM 1
#define __MBED__ 1
